VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Day6Orbit"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit
'@Folder("AdventOfCode")

'@Ignore EncapsulatePublicField, VariableNotUsed
Public Name                                               As String
'@Ignore EncapsulatePublicField
Public Parent                                             As Day6Orbit
'@Ignore EncapsulatePublicField
Public Position                                           As Long
'@Ignore EncapsulatePublicField
Public Children                                           As Kvp
    


